name: EnderBot
version: 1.3
author: codedcosmos
main: codedcosmos.enderbot.plugin.MinecraftPlugin
api-version: 1.15

commands:
  enderbackup:
    description: Backs up the world and uploads zip
    usage: /enderbackup