name: EnderBot
version: 2.1
author: codedcosmos
main: codedcosmos.enderbot.plugin.MinecraftPlugin
api-version: 1.16

commands:
  enderbackup:
    description: Backs up the world and uploads zip
    usage: /enderbackup